version: "3.8"

services:
  traefik:
    image: traefik:v2.7
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Traefik can listen to the Docker events
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./letsencrypt:/letsencrypt  # Certificates will be stored here
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"

networks:
  traefik-network:
    name: traefik-network
